language: go

sudo: required 

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - go test -v -race ./...
  - go test ./... -cover -covermode=count -coverprofile=coverage.cov
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=coverage.cov
